model_params:
  name: 'ConvAutoencoder'
  tensor_dim: 304

data_params:
  data_path: "/data/"
  image_height: 304
  image_width: 304
  train_size: 0.65
  test_size: 0.25
  val_size: 0.10
  batch_size: 64
  num_workers: 0
  pin_memory: True

trainer_params:
  min_epochs: 1
  max_epochs: 3

exp_params:
  weight_decay: 0.0
  manual_seed: 1265

early_stop:
  monitor: "loss"
  patience: 1
  min_delta: 0.00

logging_params:
  name: "Autoencoder"
  save_dir: "logs/"
  db_storage: "logs/solution.db"
