model_params:
  name: 'ConvAutoencoder'
  kernel_size: 3
  stride: 2
  padding: 1
  output_padding: 1

data_params:
  data_path: "/data/"
  data_samples: 1
  channel_dim: 3
  horizontal_dim: 304
  vertical_dim: 304
  train_size: 0.65
  test_size: 0.25
  val_size: 0.10
  batch_size: 16
  num_workers: 0
  pin_memory: True

trainer_params:
  min_epochs: 1
  max_epochs: 2

lr_finder:
  mode: "exponential" #"linear"
  num_training_steps: 100
  attr_name: "learning_rate"
  update_attr: True
  early_stop_threshold: # None # https://github.com/Lightning-AI/lightning/issues/4846#issuecomment-1014148839

exp_params:
  weight_decay: 0.0
  manual_seed: 1265
#TODO Research how to use early stop on NYU dataset
early_stop:
  monitor: "loss"
  patience: 5
  min_delta: 0.0
  mode: "min"

logging_params:
  name: "ConvAutoencoder"
  save_dir: "logs/"
  db_storage: "logs/solution.db"
