nia_search:
  evaluations: 1000
  runs: 1

model_params:
  name: 'ConvAutoencoder'
  kernel_size: 3
  stride: 2
  padding: 1
  output_padding: 1
  dilation: 1

data_params:
  data_path: "/data/"
  data_percentage: 100
  channel_dim: 3
  horizontal_dim: 304
  vertical_dim: 304
  train_size: 90 #Shared dataset
  test_size: 100 #Own dataset
  val_size: 10 #Shared dataset
  batch_size: 32
  num_workers: 0
  pin_memory: True

trainer_params:
  min_epochs: 1
  max_epochs: 20 #20

fine_tune_lr_finder:
  tune_n_epochs: 5
  lr_finder:
    mode: "exponential" #"linear"
    num_training_steps: 1
    attr_name: "learning_rate"
    update_attr: True
    early_stop_threshold: # None # https://github.com/Lightning-AI/lightning/issues/4846#issuecomment-1014148839

exp_params:
  weight_decay: 0.0
  manual_seed: 1265

early_stop:
  monitor: "loss"
  patience: 3
  min_delta: 0.0
  mode: "min"

logging_params:
  name: "ConvAutoencoder"
  logger_file: "ConvAutoencoder.log"
  save_dir: "logs/"
  db_storage: "logs/solution.db"
